# Generated by Django 3.0.2 on 2020-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.IntegerField(default=12)),
                ('created_at', models.DateField(auto_now=True, max_length=30)),
            ],
        ),
    ]
