# Generated by Django 2.2.6 on 2020-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stats', '0003_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
