# Generated by Django 2.2.6 on 2020-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stats', '0005_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Political',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
