# Generated by Django 2.2.6 on 2020-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stats', '0007_auto_20200224_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.AddField(
            model_name='business',
            name='content_url',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='null', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='business',
            name='img_url',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='business',
            name='summary',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='political',
            name='content_url',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='political',
            name='image',
            field=models.ImageField(default='null', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='political',
            name='img_url',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='political',
            name='summary',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='technology',
            name='content_url',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(default='null', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='technology',
            name='img_url',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='technology',
            name='summary',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
